# [package]
# name = "aqlfmt"
# version = "0.1.0"
# edition = "2021"

# [profile.release]
# lto = true

# [profile.dev]
# opt-level = 2

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace]
members = ["src/*"]
